macro(NTTDetectPlatform)
    if (CMAKE_SYSTEM_NAME STREQUAL "Linux")
        set(PLATFORM_DEFINITION PLATFORM_IS_LINUX)
    elseif (CMAKE_SYSTEM_NAME STREQUAL "Windows")
        set(PLATFORM_DEFINITION PLATFORM_IS_WINDOWS)
    else()
        message(FATAL "The system is not supported by this engine")
    endif()
endmacro()